Repository ByteBuildersLabs/ByteBeastsBackend, pull requests merged in 2024-10, with the labels that each got.

#78 Add maintainers
  README.md
  assets/danielcdz.everai.png
  assets/marco.everai.jpg
Labels: documentation, core-dev

#83 Feat: Pre push hook
  Makefile
  README.md
  manifests/dev/deployment/abis/models/bytebeasts-DirectionsAvailable-48430624.json
  manifests/dev/deployment/abis/models/bytebeasts-Message-23adac1f.json
  manifests/dev/deployment/abis/models/bytebeasts-Moved-2a5b60a4.json
  manifests/dev/deployment/abis/models/bytebeasts-Moves-b282ed29.json
  scripts/setup.sh
Labels: enhancement

#82 Enhance Documentation in the Project #76
  .github/templates/ISSUE_TEMPLATE.md
  .github/templates/PULL_REQUEST_TEMPLATE.md
  README.md
  docs/contribution/CONTRIBUTION.md
Labels: documentation
