Repository ByteBuildersLabs/ByteBeastsBackend, pull requests merged in 2024-12, with the labels that each got.

#101 Add tests for tournament_system
  .tool-versions
  manifests/dev/base/abis/contracts/bytebeasts-tournament_system-1f2bbf20.json
  manifests/dev/base/abis/models/bytebeasts-Tournament-12bdecb1.json
  manifests/dev/base/contracts/bytebeasts-tournament_system-1f2bbf20.toml
  manifests/dev/base/models/bytebeasts-Tournament-12bdecb1.toml
  src/lib.cairo
  src/models/tournament.cairo
  src/systems/tournament.cairo
  src/tests/test_tournament.cairo
Labels: ODHack10

#103 SeasonModel & Tests
  manifests/dev/base/abis/models/bytebeasts-Season-52f8bbb6.json
  manifests/dev/base/abis/models/bytebeasts-SeasonManager-57ed50e9.json
  manifests/dev/base/models/bytebeasts-Season-52f8bbb6.toml
  manifests/dev/base/models/bytebeasts-SeasonManager-57ed50e9.toml
  src/lib.cairo
  src/models/season.cairo
Labels: ODHack10, S, actual: 2

#100 Implement leaderboard model/entity and functions
  Scarb.lock
  Scarb.toml
  manifests/dev/base/abis/models/bytebeasts-Leaderboard-7e680376.json
  manifests/dev/base/abis/models/bytebeasts-LeaderboardEntry-7237950c.json
  manifests/dev/base/models/bytebeasts-Leaderboard-7e680376.toml
  manifests/dev/base/models/bytebeasts-LeaderboardEntry-7237950c.toml
  manifests/dev/deployment/abis/contracts/bytebeasts-tournament_system-1f2bbf20.json
  manifests/dev/deployment/abis/models/bytebeasts-Leaderboard-7e680376.json
  manifests/dev/deployment/abis/models/bytebeasts-LeaderboardEntry-7237950c.json
  manifests/dev/deployment/abis/models/bytebeasts-Tournament-12bdecb1.json
  manifests/dev/deployment/manifest.json
  manifests/dev/deployment/manifest.toml
  src/lib.cairo
  src/models/leaderboard.cairo
  src/tests/test_leaderboard.cairo
Labels: ODHack10, M, actual: 3

#97 [feat] Create an evolution PoC model
  .gitignore
  .tool-versions
  manifests/dev/base/abis/models/bytebeasts-Evolution-52744a50.json
  manifests/dev/base/models/bytebeasts-Evolution-52744a50.toml
  src/lib.cairo
  src/models/evolution.cairo
Labels: enhancement, ODHack10, S, actual: 2
